ENIGMA_IP = "192.168.0.37"
ENIGMA_GET_ALL_SERVICES= "http://{ENIGMA_IP}/web/getservices"
ENIGMA_GET_ONE_SERVICE= "http://{ENIGMA_IP}/web/getservices?sRef={service_reference}"
FFMPEG_RUN_SCRIPT_TEMPLATE_NAME="run_ffmpeg_transcode_template.sh"
FFMPEG_RUN_SCRIPT_NAME="run_ffmpeg_transcode.sh"